'use client';
import { useEffect, useState } from 'react';
import { flushSync } from 'react-dom';
import { Progress } from '@/components/ui/progress';
import { MapPin, Route, Search, ArrowUpRight, Check, Plus, ArrowUp, ArrowDown, X, Footprints, ScanEye, Navigation, Download } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import places from './places.json';
type RecordData={date:string;note:string};
const regions=[...new Set(places.map(p=>p.region))];
const key='peace-field-guide-v1';
const today=()=>new Date().toLocaleDateString('sv-SE');
const enc=encodeURIComponent;
export default function Home(){
 const [selected,setSelected]=useState(1),[search,setSearch]=useState(''),[region,setRegion]=useState('전체'),[filter,setFilter]=useState('전체'),[records,setRecords]=useState<Record<string,RecordData>>({}),[route,setRoute]=useState<number[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[road,setRoad]=useState(false);
 const p=places.find(x=>x.id===selected)!;
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const d=JSON.parse(raw);if(d.records&&typeof d.records==='object')setRecords(Object.fromEntries(Object.entries(d.records).filter(([id,v])=>places.some(p=>p.id===Number(id))&&!!v&&typeof (v as RecordData).date==='string'&&typeof (v as RecordData).note==='string')) as Record<string,RecordData>);if(Array.isArray(d.route))setRoute([...new Set(d.route.filter((id:unknown)=>typeof id==='number'&&places.some(p=>p.id===id)))] as number[]);}}catch{setError('저장된 기록을 불러오지 못했습니다. 브라우저 저장 설정을 확인해 주세요.');}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify({records,route}))}catch{setError('브라우저에 저장하지 못했습니다. 기록 내보내기로 보관해 주세요.')}},[records,route,ready]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
  const ctx=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!ctx?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(ctx.registerTool({name:'select_statue',description:'Find a statue by guide ID and open its map and field guide in the visible page.',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:1,maximum:79}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){const id=(input as {id?:unknown})?.id;if(typeof id!=='number'||!Number.isInteger(id)||!places.some(p=>p.id===id))throw new Error('Valid guide ID 1–79 required');flushSync(()=>{setSelected(id);setRoad(false)});return {selected:places.find(p=>p.id===id)}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 const visited=places.filter(x=>records[x.id]?.date).length;
 const visible=places.filter(x=>(region==='전체'||x.region===region)&&(filter==='전체'||(filter==='방문 완료'?!!records[x.id]?.date:filter==='아직 안 간 곳'?!records[x.id]?.date:route.includes(x.id)))&&`${x.name} ${x.address} ${x.detail}`.includes(search.trim()));
 const select=(id:number)=>{setSelected(id);setRoad(false)};
 const update=(id:number,patch:Partial<RecordData>)=>setRecords(old=>({...old,[id]:{...(old[id]||{date:'',note:''}),...patch}}));
 const toggle=(id:number)=>setRoute(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 const move=(index:number,delta:number)=>setRoute(old=>{const n=[...old];if(index+delta<0||index+delta>=n.length)return old;[n[index],n[index+delta]]=[n[index+delta],n[index]];return n});
 const query=(id:number)=>{const x=places.find(p=>p.id===id)!;return x.id===4?'서울 성북천 분수마루':x.id===64?'광주 양림동 52-4':x.query};
 const directions=(a:number,b:number)=>`https://www.google.com/maps/dir/?api=1&origin=${enc(query(a))}&destination=${enc(query(b))}&travelmode=transit`;
 const exportData=()=>{const data={version:1,exportedAt:new Date().toISOString(),route:route.map(id=>({id,name:places.find(p=>p.id===id)!.name})),records:places.filter(p=>records[p.id]).map(p=>({id:p.id,name:p.name,...records[p.id]}))};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='평화의-발걸음-답사기록.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 return <main>
  <header className="topbar"><div className="brand"><span className="brandmark"><Footprints size={24}/></span><div><h1>평화의 발걸음</h1><span>전국 소녀상 답사 지도</span></div></div><div className="topright"><span className="saved"><i/>이 브라우저에 기록</span><button className="quiet" onClick={exportData}><Download size={16}/><span>기록 내보내기</span></button></div></header>
  <div className="workspace">
   <aside className="catalog"><div className="catalog-head"><div className="eyebrow">FIELD GUIDE · 79 PLACES</div><h2>기억을 따라 걷는 길</h2><div className="summary"><strong>{visited}<small> / 79곳 방문</small></strong><span>{Math.round(visited/79*100)}%</span></div><Progress className="visit-progress" value={visited} max={79} aria-label="방문 진행률"/><label className="searchbox"><Search size={18}/><input aria-label="소녀상 이름이나 장소 검색" placeholder="이름, 주소, 장소 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="filters"><Select value={region} onValueChange={v=>setRegion(v||'전체')}><SelectTrigger aria-label="지역 선택"><SelectValue>{region==='전체'?'전국 모든 지역':region}</SelectValue></SelectTrigger><SelectContent>{['전체',...regions].map(r=><SelectItem key={r} value={r}>{r==='전체'?'전국 모든 지역':r}</SelectItem>)}</SelectContent></Select><Select value={filter} onValueChange={v=>setFilter(v||'전체')}><SelectTrigger aria-label="방문 상태 선택"><SelectValue/></SelectTrigger><SelectContent>{['전체','아직 안 간 곳','방문 완료','내 동선'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="result-label">답사 장소 <b>{visible.length}</b><span>2026.09.10 자료 기준</span></div><div className="place-list">{visible.length===0?<div className="empty">조건에 맞는 장소가 없습니다.<button className="quiet" onClick={()=>{setSearch('');setRegion('전체');setFilter('전체')}}>필터 초기화</button></div>:visible.map(x=><button className={`place ${selected===x.id?'selected':''}`} key={x.id} onClick={()=>select(x.id)} aria-pressed={selected===x.id}><span className={`place-number ${records[x.id]?.date?'done':''}`}>{records[x.id]?.date?<Check size={16}/>:String(x.id).padStart(2,'0')}</span><span className="place-copy"><span className="place-region">{x.region}{route.includes(x.id)&&<em>동선 {route.indexOf(x.id)+1}</em>}</span><strong>{x.name}</strong><small>{x.detail.split('▶')[0]}</small></span><span className="place-arrow">↗</span></button>)}</div>
    <footer>출처: 제공된 현장 답사 가이드 · 79곳<br/>전국 전체 설치 목록을 뜻하지 않습니다.</footer>
   </aside>
   <section className="main-panel" aria-label="선택한 장소"><div className="map-heading"><span><MapPin size={17}/>{p.region} <b>/</b> {p.name}</span><a href={`https://map.naver.com/p/search/${enc(query(p.id))}`} target="_blank" rel="noreferrer">네이버지도 <ArrowUpRight size={16}/></a></div>
    <div className="map-wrap"><iframe key={p.id} title={`${p.name} 지도 검색 결과`} src={`https://maps.google.com/maps?q=${enc(query(p.id))}&hl=ko&z=16&output=embed`} referrerPolicy="no-referrer-when-downgrade" loading="lazy" allowFullScreen/><div className="map-label"><span className="live-dot"/> 장소명 검색 지도 · 현장 설명과 핀을 함께 확인하세요</div></div>
    <article className="detail"><div className="detail-title"><div><div className="eyebrow">{p.region} · GUIDE {String(p.id).padStart(2,'0')}</div><h2>{p.name}</h2><p className="address"><MapPin size={16}/>{p.address==='-'?'도로명주소 미기재 · 아래 현장 위치 참고':p.address}</p></div><button className={`route-add ${route.includes(p.id)?'added':''}`} disabled={!ready} onClick={()=>toggle(p.id)}>{route.includes(p.id)?<Check size={17}/>:<Plus size={17}/>} {route.includes(p.id)?'동선에 담김':'동선에 추가'}</button></div>
     <div className="location-detail"><div><span className="section-label">현장에서 찾기</span><p>{p.detail.split('▶')[0]}</p>{p.detail.includes('▶')&&<p className="howto"><Navigation size={15}/>{p.detail.split('▶')[1]}</p>}</div>{p.note&&<div className="note"><span>답사 참고</span><p>{p.note}</p></div>}</div>
     <div className="action-row"><a className="action" href={`https://map.kakao.com/link/search/${enc(query(p.id))}`} target="_blank" rel="noreferrer"><Navigation size={17}/>카카오맵 길찾기<ArrowUpRight size={15}/></a><button className={`action ${road?'active':''}`} onClick={()=>setRoad(!road)} aria-expanded={road}><ScanEye size={18}/>거리뷰 보기</button></div>
     {road&&<div className="road-panel"><b>주변 도로를 미리 둘러보세요</b><p>{p.id===34?'PDF에 기재된 좌표로 주변 로드뷰를 엽니다.':'카카오맵에서 해당 장소를 선택한 뒤 ‘로드뷰’를 누르세요. 원문에 좌표가 없어 장소 검색으로 연결합니다.'} 공원 안·학교 안은 촬영 영상이 없을 수 있습니다.</p><a target="_blank" rel="noreferrer" href={p.id===34?'https://map.kakao.com/link/roadview/36.49633,127.27339':`https://map.kakao.com/link/search/${enc(query(p.id))}`}>{p.id===34?'주변 로드뷰 열기':'카카오맵에서 장소 선택'} <ArrowUpRight size={16}/></a></div>}
     <div className="visit-record"><div className="visit-head"><label><Checkbox checked={!!records[p.id]?.date} disabled={!ready} onCheckedChange={v=>update(p.id,{date:v?today():''})}/><strong>다녀왔어요</strong></label>{records[p.id]?.date?<input type="date" aria-label="방문 날짜" value={records[p.id].date} onChange={e=>update(p.id,{date:e.target.value})}/>:<span>방문하면 체크해 주세요</span>}</div><textarea disabled={!ready} aria-label="답사 메모" placeholder="현장 메모를 남겨보세요. 입구, 촬영 위치, 느낀 점…" value={records[p.id]?.note||''} onChange={e=>update(p.id,{note:e.target.value})}/><small>방문 날짜와 메모는 자동 저장됩니다. 다른 기기와 동기화되지 않습니다.</small></div>
    </article>
   </section>
   <aside className="itinerary"><div className="itinerary-heading"><span className="route-icon"><Route size={22}/></span><div><h2>나의 답사 동선</h2><p>{route.length}곳을 이어 걷기</p></div></div><p className="route-description">갈 곳을 담고, 이동 순서를 정하세요.</p>{route.length===0?<div className="route-empty"><div className="empty-line"><span>1</span><i/><span>2</span><i/><span>3</span></div><strong>첫 번째 장소를 담아보세요</strong><p>장소의 ‘동선에 추가’를 누르면<br/>여기서 방문 순서를 정할 수 있어요.</p><button className="route-add" onClick={()=>toggle(p.id)} disabled={!ready}><Plus size={16}/>현재 장소 담기</button></div>:<ol className="route-list">{route.map((id,i)=>{const x=places.find(p=>p.id===id)!;return <li key={id}><div className="route-stop"><span className="stop-number">{i+1}</span><button className="stop-name" onClick={()=>select(id)}><small>{x.region} {records[id]?.date?'· 방문 완료':''}</small><strong>{x.name}</strong></button><button className="iconbutton" aria-label={`${x.name} 동선에서 제거`} onClick={()=>toggle(id)}><X size={16}/></button></div><div className="stop-controls"><button disabled={i===0} aria-label={`${x.name} 위로`} onClick={()=>move(i,-1)}><ArrowUp size={14}/></button><button disabled={i===route.length-1} aria-label={`${x.name} 아래로`} onClick={()=>move(i,1)}><ArrowDown size={14}/></button>{i<route.length-1&&<a href={directions(id,route[i+1])} target="_blank" rel="noreferrer">다음 장소 길찾기 ↗</a>}</div></li>})}</ol>}<div className="route-help"><b>이동 거리·시간 확인</b><p>구간별 길찾기를 열면 지도 서비스에서 대중교통 경로와 시간을 확인할 수 있습니다. 선택한 순서가 자동 최단 경로는 아닙니다.</p></div><div className="source-note"><span>답사 전 확인</span><p>이전 여부와 정확한 위치는 지도·현장에서 다시 확인하세요. 학교 안 장소는 출입·촬영 허가가 필요합니다.</p><small>제공 PDF {p.page}쪽 · 원문 위치 설명 반영</small></div></aside>
  </div>{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="알림 닫기">×</button></div>}
 </main>
}
