'use client';
import { useEffect, useState } from 'react';
import { flushSync } from 'react-dom';
import { Progress } from '@/components/ui/progress';
import { MapPin, Route, Search, ArrowUpRight, Check, Plus, ArrowUp, ArrowDown, X, Landmark, Map, BookOpen, CircleHelp, Info, Copy, Printer, ArrowDownUp, Shield, ScanEye, Navigation, Download } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import places from './places.json';
import {resolvePoint,buildNaverTransitUrl,buildNaverStreetViewUrl,naverStreetViews} from '@/lib/naver-directions';
type RecordData={date:string;note:string};
const regions=[...new Set(places.map(p=>p.region))];
const key='peace-field-guide-v1';
const today=()=>new Date().toLocaleDateString('sv-SE');
const enc=encodeURIComponent;
export default function Home(){
 const [openingRoad,setOpeningRoad]=useState<number|null>(null);
 const [selected,setSelected]=useState(1),[search,setSearch]=useState(''),[region,setRegion]=useState('전체'),[filter,setFilter]=useState('전체'),[records,setRecords]=useState<Record<string,RecordData>>({}),[route,setRoute]=useState<number[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(''),[road,setRoad]=useState(false),[alphabetical,setAlphabetical]=useState(false),[copied,setCopied]=useState(false),[routing,setRouting]=useState<string|null>(null);
 const p=places.find(x=>x.id===selected)!;
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const d=JSON.parse(raw);if(d.records&&typeof d.records==='object')setRecords(Object.fromEntries(Object.entries(d.records).filter(([id,v])=>places.some(p=>p.id===Number(id))&&!!v&&typeof (v as RecordData).date==='string'&&typeof (v as RecordData).note==='string')) as Record<string,RecordData>);if(Array.isArray(d.route))setRoute([...new Set(d.route.filter((id:unknown)=>typeof id==='number'&&places.some(p=>p.id===id)))] as number[]);}}catch{setError('저장된 기록을 불러오지 못했습니다. 브라우저 저장 설정을 확인해 주세요.');}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify({records,route}))}catch{setError('브라우저에 저장하지 못했습니다. 기록 내보내기로 보관해 주세요.')}},[records,route,ready]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
  const ctx=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!ctx?.registerTool)return;
  const lifecycle=new AbortController();
  try{void Promise.resolve(ctx.registerTool({name:'select_statue',description:'Find a statue by guide ID and open its map and field guide in the visible page.',inputSchema:{type:'object',properties:{id:{type:'integer',minimum:1,maximum:79}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){const id=(input as {id?:unknown})?.id;if(typeof id!=='number'||!Number.isInteger(id)||!places.some(p=>p.id===id))throw new Error('Valid guide ID 1–79 required');flushSync(()=>{setSelected(id);setRoad(false)});return {selected:places.find(p=>p.id===id)}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 const visited=places.filter(x=>records[x.id]?.date).length;
 const visible=places.filter(x=>(region==='전체'||x.region===region)&&(filter==='전체'||(filter==='방문 완료'?!!records[x.id]?.date:filter==='아직 안 간 곳'?!records[x.id]?.date:route.includes(x.id)))&&`${x.name} ${x.address} ${x.detail}`.includes(search.trim())).sort((a,b)=>alphabetical?a.name.localeCompare(b.name,'ko'):a.id-b.id);
 const select=(id:number)=>{setSelected(id);setRoad(false)};
 const update=(id:number,patch:Partial<RecordData>)=>setRecords(old=>({...old,[id]:{...(old[id]||{date:'',note:''}),...patch}}));
 const toggle=(id:number)=>setRoute(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id]);
 const move=(index:number,delta:number)=>setRoute(old=>{const n=[...old];if(index+delta<0||index+delta>=n.length)return old;[n[index],n[index+delta]]=[n[index+delta],n[index]];return n});
 const query=(id:number)=>{const x=places.find(p=>p.id===id)!;return x.id===4?'서울 성북천 분수마루':x.id===64?'광주 양림동 52-4':x.query};
 const openStreetView=async()=>{
  if(openingRoad!==null)return;
  const target=p;
  setRoad(true);setError('');
  if(naverStreetViews[target.id]){window.open(naverStreetViews[target.id],'_blank','noopener,noreferrer');return;}
  const popup=window.open('about:blank','_blank');
  if(!popup){setError('거리뷰를 열려면 이 사이트의 팝업을 허용해 주세요.');return;}
  popup.opener=null;popup.document.title='네이버 거리뷰 연결 중';popup.document.body.textContent=`${target.name}의 거리뷰를 여는 중입니다…`;
  setOpeningRoad(target.id);
  try{
   const url=naverStreetViews[target.id]||buildNaverStreetViewUrl(await resolvePoint(target,{streetView:true}));
   if(!popup.closed)popup.location.replace(url);
  }catch(e){popup.close();setError(e instanceof Error?e.message:'거리뷰 위치를 확인하지 못했습니다. 다시 시도해 주세요.');}
  finally{setOpeningRoad(null);}
 };
 const directions=async(a:number,b:number)=>{
  if(routing)return;
  const popup=window.open('about:blank','_blank');
  if(!popup){setError('길찾기를 열려면 이 사이트의 팝업을 허용해 주세요.');return;}
  popup.opener=null;popup.document.title='네이버 대중교통 연결 중';popup.document.body.textContent='등록한 출발지와 도착지를 네이버지도에 입력하고 있습니다…';
  setRouting(`${a}-${b}`);setError('');
  try{const start=places.find(p=>p.id===a)!,end=places.find(p=>p.id===b)!;const [from,to]=await Promise.all([resolvePoint(start),resolvePoint(end)]);popup.location.replace(buildNaverTransitUrl(start,from,end,to));}
  catch(e){popup.close();setError(e instanceof Error?e.message:'위치를 확인하지 못했습니다. 다시 시도해 주세요.');}
  finally{setRouting(null);}
 };
 const exportData=()=>{const data={version:1,exportedAt:new Date().toISOString(),route:route.map(id=>({id,name:places.find(p=>p.id===id)!.name})),records:places.filter(p=>records[p.id]).map(p=>({id:p.id,name:p.name,...records[p.id]}))};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='평화의-발걸음-답사기록.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const resetFilters=()=>{setSearch('');setRegion('전체');setFilter('전체')};
 const copyAddress=async()=>{try{await navigator.clipboard.writeText(p.address==='-'?p.detail:p.address);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('주소를 복사하지 못했습니다. 주소 텍스트를 직접 선택해 복사해 주세요.')}};
 const exportRoute=()=>{const text=route.map((id,i)=>{const x=places.find(p=>p.id===id)!;return `${i+1}. ${x.name}\n${x.address==='-'?'':x.address}\n${x.detail}\n${records[id]?.date?'방문: '+records[id].date:'미방문'}\n${records[id]?.note||''}`}).join('\n\n');const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='소녀상-답사-동선.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 return <main>
  <header className="topbar"><a className="brand" href="#map"><span className="brandmark"><Landmark size={24}/></span><div><div className="brand-title"><h1>소녀상 트래커</h1><span className="archive-badge"><BookOpen size={13}/>답사 아카이브</span></div><span>전국 평화의 소녀상 답사 기록 (총 79곳)</span></div></a><nav className="topnav" aria-label="주요 메뉴"><a href="#map" className="nav-active"><Map size={17}/>현장 답사 지도</a><a href="#catalog" onClick={resetFilters}><BookOpen size={17}/>소녀상 수록 목록</a><a href="#guide"><CircleHelp size={17}/>답사 안내서</a></nav><div className="topright"><span className="saved"><i/>{!ready?'기록 불러오는 중':error?'저장 상태 확인 필요':'로컬 저장됨 (브라우저 보관)'}<Info size={15}/></span><button className="quiet" onClick={exportData}><Download size={17}/><span>기록 내보내기</span></button><button className="quiet print-guide" onClick={()=>window.print()}><Printer size={17}/><span>답사 가이드</span></button></div></header>
  <div className="workspace">
   <aside className="catalog" id="catalog"><div className="catalog-head"><div className="summary"><strong>전체 답사 현황</strong><span><b>{visited} / 79곳</b> ({(visited/79*100).toFixed(1)}%)</span></div><Progress className="visit-progress" value={visited} max={79} aria-label="방문 진행률"/><div className="source-version"><span>PDF 답사 가이드 79개소 수록 기준</span><span>2026.09.10</span></div></div><div className="filter-panel"><label className="searchbox"><Search size={20}/><input aria-label="소녀상 이름이나 장소 검색" placeholder="이름, 주소, 현장 장소 검색" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="검색어 지우기" onClick={()=>setSearch('')}><X size={18}/></button>}</label><div className="filters"><Select value={region} onValueChange={v=>setRegion(v||'전체')}><SelectTrigger aria-label="지역 선택"><SelectValue>{region==='전체'?'전국 17개 시도 (79곳)':`${region} (${places.filter(p=>p.region===region).length}곳)`}</SelectValue></SelectTrigger><SelectContent>{['전체',...regions].map(r=><SelectItem key={r} value={r}>{r==='전체'?'전국 17개 시도 (79곳)':`${r} (${places.filter(p=>p.region===r).length}곳)`}</SelectItem>)}</SelectContent></Select><button className="quiet sort-button" onClick={()=>setAlphabetical(!alphabetical)} aria-pressed={alphabetical}><ArrowDownUp size={16}/>{alphabetical?'가이드순':'가나다순'}</button></div><div className="filter-chips" aria-label="방문 상태 필터">{[['전체','전체',79],['아직 안 간 곳','미방문',79-visited],['방문 완료','방문 완료',visited],['내 동선','내 동선',route.length]].map(([value,label,count])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(String(value))} aria-pressed={filter===value}>{label} {count}</button>)}</div></div>
    <div className="place-list">{visible.length===0?<div className="empty">조건에 맞는 장소가 없습니다.<button className="quiet" onClick={resetFilters}>필터 초기화</button></div>:visible.map(x=><button className={`place ${selected===x.id?'selected':''}`} key={x.id} onClick={()=>select(x.id)} aria-pressed={selected===x.id}><span className="place-meta"><span className="region-tag">{x.region}</span><span className={`status-tag ${records[x.id]?.date?'done':''}`}>{records[x.id]?.date?<><Check size={13}/>방문 완료</>:'미방문'}</span>{route.includes(x.id)&&<span className="route-tag">동선 {route.indexOf(x.id)+1}번</span>}</span><strong>{x.name}</strong><span className="place-description">{x.detail.split('▶')[0]}</span><span className="place-bottom"><span>수록 번호: {String(x.id).padStart(3,'0')}</span><span>{records[x.id]?.date?`방문: ${records[x.id].date}`:`가이드 ${x.page}쪽`}</span></span></button>)}</div>
    <footer><span>표시 중: {visible.length}개소 / 전체 79개소</span><button onClick={resetFilters}>필터 초기화</button></footer>
   </aside>
   <section className="main-panel" aria-label="선택한 장소" id="map"><div className="map-wrap"><iframe key={p.id} title={`${p.name} 지도 검색 결과`} src={`https://maps.google.com/maps?q=${enc(query(p.id))}&hl=ko&z=16&output=embed`} referrerPolicy="no-referrer-when-downgrade" loading="lazy" allowFullScreen/><div className="map-notice"><Info size={21}/><div><span>좌표 정밀도</span><p>제공 가이드의 장소명 검색 결과입니다. 현장 보행 지형 및 현판 설명문을 함께 대조하세요.</p></div><small><MapPin size={13}/>현장 대조 권장</small></div></div>
    <div className="detail-content"><article className="detail"><div className="detail-tags"><span className="region-tag"><Landmark size={15}/>{p.region}</span>{records[p.id]?.date&&<span className="status-tag done"><Check size={15}/>답사 완료 ({records[p.id].date})</span>}<span className="record-id"># GUIDE-{String(p.id).padStart(3,'0')}</span></div><h2>{p.name}</h2><div className="address-row"><p className="address"><MapPin size={20}/>{p.address==='-'?'도로명주소 미기재 · 현장 위치 참고':p.address}</p><button className="small-action" onClick={copyAddress}><Copy size={15}/>{copied?'복사됨':'주소 복사'}</button></div><button className={`small-action street-button ${road?'active':''}`} onClick={openStreetView} disabled={openingRoad!==null} aria-busy={openingRoad===p.id}><ScanEye size={16}/>{openingRoad===p.id?'거리뷰 연결 중…':'네이버 거리뷰 바로 보기'}</button>
     {road&&<div className="road-panel" role="status"><b>{p.name} 거리뷰</b><p>{naverStreetViews[p.id]?'선택한 소녀상의 네이버 장소와 연결된 거리뷰를 바로 엽니다.':'가이드의 위치를 자동으로 입력해 가장 가까운 거리뷰를 엽니다. 촬영 지점에 따라 소녀상이 화면에 보이지 않을 수 있습니다.'} 영상이 없거나 위치가 다르면 아래에서 장소를 확인해 주세요.</p><a target="_blank" rel="noreferrer" href={`https://map.naver.com/p/search/${enc(query(p.id))}`}>네이버지도에서 위치 확인 <ArrowUpRight size={16}/></a></div>}
     <div className="action-row"><button className="route-add" disabled={!ready} onClick={()=>toggle(p.id)}>{route.includes(p.id)?<Check size={18}/>:<Plus size={18}/>} {route.includes(p.id)?`동선 ${route.indexOf(p.id)+1}번 담김`:'동선에 추가'}</button><a className="action" href={`https://map.kakao.com/link/search/${enc(query(p.id))}`} target="_blank" rel="noreferrer"><Navigation size={18}/>카카오맵 길찾기</a><a className="action" href={`https://map.naver.com/p/search/${enc(query(p.id))}`} target="_blank" rel="noreferrer"><MapPin size={18}/>네이버지도</a></div></article>
     <div className="info-grid"><article className="info-card"><h3><Navigation size={21}/>설치 위치 및 접근</h3><p>{p.detail.split('▶')[0]}</p>{p.detail.includes('▶')&&<p className="howto">{p.detail.split('▶')[1]}</p>}<small>현장 위치 안내 · 제공 PDF {p.page}쪽</small></article><article className="info-card" id="guide"><h3><Shield size={21}/>현장 답사 주의사항</h3><p>{p.note||'현장의 안내 표지와 보행 질서를 확인해 주세요.'}</p><p className="howto">학교 안 장소는 사전 출입·촬영 허가를 확인하세요. 위치 이전 여부는 답사 전 다시 확인해 주세요.</p><small>원문 기준 · 현장 확인 필요</small></article></div>
     <article className="visit-record"><div className="visit-head"><label><Checkbox checked={!!records[p.id]?.date} disabled={!ready} onCheckedChange={v=>update(p.id,{date:v?today():''})}/><strong>다녀왔어요</strong></label>{records[p.id]?.date?<input type="date" aria-label="방문 날짜" value={records[p.id].date} onChange={e=>update(p.id,{date:e.target.value})}/>:<span>방문하면 체크해 주세요</span>}</div><textarea disabled={!ready} aria-label="답사 메모" placeholder="현장 메모를 남겨보세요. 입구, 촬영 위치, 느낀 점…" value={records[p.id]?.note||''} onChange={e=>update(p.id,{note:e.target.value})}/><small>이 브라우저에 자동 저장됩니다. 다른 기기와 동기화되지 않습니다.</small></article>
    </div>
   </section>
   <aside className="itinerary" aria-label="답사 동선"><div className="itinerary-heading"><div><h2>나의 답사 동선 <span>{route.length}곳</span></h2><p>현장 방문 순서를 직접 조정하세요</p></div></div><div className="route-help"><Info size={17}/><p>등록한 동선의 출발·도착지를 자동 입력합니다. 좌표가 없는 곳은 가이드 주소·접근 지점 기준이므로 현장 위치를 함께 확인하세요.</p></div><div className="itinerary-body">{route.length===0?<div className="route-empty"><MapPin size={28}/><strong>첫 번째 답사지를 담아보세요</strong><p>장소의 ‘동선에 추가’를 누르면<br/>이곳에 순서대로 담깁니다.</p><button className="route-add" onClick={()=>toggle(p.id)} disabled={!ready}><Plus size={16}/>현재 장소 담기</button></div>:<ol className="route-list">{route.map((id,i)=>{const x=places.find(p=>p.id===id)!;return <li key={id}><div className={`stop-card ${id===p.id?'selected':''}`}><div className="route-stop"><span className="stop-number">{i+1}</span><button className="stop-name" onClick={()=>select(id)}><small>{x.region}</small><strong>{x.name}</strong><span>{x.address==='-'?x.detail.split('▶')[0]:x.address}</span></button><div className="stop-controls"><button disabled={i===0} aria-label={`${x.name} 위로`} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button disabled={i===route.length-1} aria-label={`${x.name} 아래로`} onClick={()=>move(i,1)}><ArrowDown size={16}/></button></div></div><div className="stop-status"><span className={records[id]?.date?'visited':''}>{records[id]?.date?<><Check size={15}/>답사 완료</>:'미방문 (예정지)'}</span><button aria-label={`${x.name} 동선에서 제거`} onClick={()=>toggle(id)}>동선 제외</button></div></div>{i<route.length-1&&<div className="route-segment"><span>{x.region!==places.find(p=>p.id===route[i+1])!.region?'지역 간 이동':'다음 행선지'}</span><button className="transit-link" disabled={!!routing} onClick={()=>directions(id,route[i+1])} title={`${x.name} → ${places.find(p=>p.id===route[i+1])!.name}: 출발·도착 자동 입력`}>{routing===`${id}-${route[i+1]}`?'위치 확인 중…':'네이버 대중교통'}<ArrowUpRight size={14}/></button></div>}</li>})}</ol>}{route.length>0&&<div className="route-hint"><MapPin size={25}/><p>장소 목록에서 <b>‘동선에 추가’</b>를 누르면<br/>이곳에 순서대로 담깁니다.</p><small>선택한 순서 · 자동 최단 경로 아님</small></div>}</div><div className="itinerary-footer"><button className="route-add" disabled={!route.length} onClick={()=>window.print()}><Printer size={18}/>동선 요약 인쇄 / PDF 저장</button><button className="action" disabled={!route.length} onClick={exportRoute}><Copy size={17}/>일정 텍스트로 내보내기</button><small>출처: 제공된 가이드 79곳 · 위치 변환: Esri · 전국 전체 설치 목록 아님</small></div></aside>
  </div>{error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="알림 닫기">×</button></div>}
 </main>
}
